import '../models/plot_model.dart';

/// Local preview data used only when the administrator-owned Firestore
/// collections have not been populated yet.
///
/// Firestore remains the primary source of truth. As soon as live `plots` or
/// `dealers` documents exist, the screens automatically use those records and
/// stop showing this preview data.
class DemoData {
  DemoData._();

  static const List<Map<String, dynamic>> plotMaps = [
    {
      '_id': 'plot_245',
      'plotNumber': '245',
      'block': 'B',
      'phase': '2',
      'size': '10 Marla',
      'plotType': 'Residential',
      'category': 'Residential',
      'status': 'Available',
      'roadWidth': '40 ft',
      'facing': 'North',
      'dimensions': '35 ft x 65 ft',
      'developmentPercent': 65,
      'price': 8500000,
      'location': 'Phase 2, Block B',
      'notes': 'Corner plot with park access and a wide approach road.',
      'featured': true,
      'imageUrl': '',
    },
    {
      '_id': 'plot_236',
      'plotNumber': '236',
      'block': 'B',
      'phase': '2',
      'size': '5 Marla',
      'plotType': 'Residential',
      'category': 'Residential',
      'status': 'Available',
      'roadWidth': '40 ft',
      'facing': 'East',
      'dimensions': '25 ft x 45 ft',
      'developmentPercent': 82,
      'price': 4950000,
      'location': 'Phase 2, Block B',
      'notes': 'Park-side residential plot near the central green.',
      'featured': false,
      'imageUrl': '',
    },
    {
      '_id': 'plot_244',
      'plotNumber': '244',
      'block': 'B',
      'phase': '2',
      'size': '10 Marla',
      'plotType': 'Residential',
      'category': 'Residential',
      'status': 'Reserved',
      'roadWidth': '40 ft',
      'facing': 'West',
      'dimensions': '35 ft x 65 ft',
      'developmentPercent': 74,
      'price': 8250000,
      'location': 'Phase 2, Block B',
      'notes': 'Premium residential plot close to the main boulevard.',
      'featured': false,
      'imageUrl': '',
    },
    {
      '_id': 'plot_202',
      'plotNumber': '202',
      'block': 'C',
      'phase': '2',
      'size': '1 Kanal',
      'plotType': 'Residential',
      'category': 'Residential',
      'status': 'Available',
      'roadWidth': '60 ft',
      'facing': 'South',
      'dimensions': '50 ft x 90 ft',
      'developmentPercent': 88,
      'price': 15750000,
      'location': 'Phase 2, Block C',
      'notes': 'Large plot with direct access to a 60 ft road.',
      'featured': true,
      'imageUrl': '',
    },
    {
      '_id': 'plot_210',
      'plotNumber': '210',
      'block': 'C',
      'phase': '2',
      'size': '10 Marla',
      'plotType': 'Residential',
      'category': 'Residential',
      'status': 'Reserved',
      'roadWidth': '40 ft',
      'facing': 'North-West',
      'dimensions': '35 ft x 65 ft',
      'developmentPercent': 76,
      'price': 8900000,
      'location': 'Phase 2, Block C',
      'notes': 'Near community amenities and commercial access.',
      'featured': false,
      'imageUrl': '',
    },
  ];

  static List<PlotModel> get plotModels {
    return plotMaps.map((data) {
      return PlotModel(
        id: data['_id']! as String,
        plotNumber: data['plotNumber']! as String,
        plotType: data['plotType']! as String,
        size: data['size']! as String,
        location: data['location']! as String,
        price: data['price']! as int,
        status: data['status']! as String,
        allocatedTo: '',
        block: data['block']! as String,
        phase: data['phase']! as String,
        category: data['category']! as String,
        roadWidth: data['roadWidth']! as String,
        facing: data['facing']! as String,
        dimensions: data['dimensions']! as String,
        developmentPercent: data['developmentPercent']! as int,
        imageUrl: data['imageUrl']! as String,
        notes: data['notes']! as String,
        featured: data['featured']! as bool,
      );
    }).toList(growable: false);
  }

  static const List<Map<String, dynamic>> dealers = [
    {
      '_id': 'skyline_associates',
      'companyName': 'Skyline Associates',
      'name': 'Skyline Associates',
      'licenseNumber': 'DHS-VD-24-0178',
      'city': 'Lahore',
      'specialization': 'Residential Plots, Commercial Plots',
      'phone': '0312-3456789',
      'email': 'skyline@example.com',
      'businessAddress': 'Main Boulevard, Lahore',
      'verificationStatus': 'verified',
      'logoAsset': 'assets/dealers/skyline_associates.png',
    },
    {
      '_id': 'nexus_properties',
      'companyName': 'Nexus Properties',
      'name': 'Nexus Properties',
      'licenseNumber': 'DHS-VD-24-0093',
      'city': 'Islamabad',
      'specialization': 'Residential Plots, Farm Houses',
      'phone': '0333-9876543',
      'email': 'nexus@example.com',
      'businessAddress': 'Blue Area, Islamabad',
      'verificationStatus': 'verified',
      'logoAsset': 'assets/dealers/nexus_properties.png',
    },
    {
      '_id': 'premier_estates',
      'companyName': 'Premier Estates',
      'name': 'Premier Estates',
      'licenseNumber': 'DHS-VD-24-0211',
      'city': 'Karachi',
      'specialization': 'Commercial Plots, Apartments',
      'phone': '0300-1234567',
      'email': 'premier@example.com',
      'businessAddress': 'Shahrah-e-Faisal, Karachi',
      'verificationStatus': 'verified',
      'logoAsset': 'assets/dealers/premier_estates.png',
    },
  ];
}
