// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF0T_dQcnj3Kd_o233SncdVgO0ePtJXis',
    appId: '1:969765136421:web:fb40ebb19165b1a7cc37cc',
    messagingSenderId: '969765136421',
    projectId: 'digital-housing-society-2f27c',
    authDomain: 'digital-housing-society-2f27c.firebaseapp.com',
    storageBucket: 'digital-housing-society-2f27c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLF6BjT8FCTBxWVFP3nKW31g6oSu-oyLQ',
    appId: '1:969765136421:android:15e1d1e865749ce6cc37cc',
    messagingSenderId: '969765136421',
    projectId: 'digital-housing-society-2f27c',
    storageBucket: 'digital-housing-society-2f27c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYLYDWRKLqxu31yNdHLufp9TZSIizK6-E',
    appId: '1:969765136421:ios:f1d7825e70f26eb0cc37cc',
    messagingSenderId: '969765136421',
    projectId: 'digital-housing-society-2f27c',
    storageBucket: 'digital-housing-society-2f27c.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYLYDWRKLqxu31yNdHLufp9TZSIizK6-E',
    appId: '1:969765136421:ios:f1d7825e70f26eb0cc37cc',
    messagingSenderId: '969765136421',
    projectId: 'digital-housing-society-2f27c',
    storageBucket: 'digital-housing-society-2f27c.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF0T_dQcnj3Kd_o233SncdVgO0ePtJXis',
    appId: '1:969765136421:web:86cf78648b9dbc22cc37cc',
    messagingSenderId: '969765136421',
    projectId: 'digital-housing-society-2f27c',
    authDomain: 'digital-housing-society-2f27c.firebaseapp.com',
    storageBucket: 'digital-housing-society-2f27c.firebasestorage.app',
  );
}
