name: digital_housing_society
description: Premium Flutter Admin Panel for Digital Housing Society.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.14.0
  google_fonts: ^6.1.0
  cloud_firestore: ^6.9.0
  firebase_auth: ^6.5.7
  pdf: ^3.11.1
  printing: ^5.13.4
  excel: ^4.0.6
  share_plus: ^10.1.4
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.0
  http: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/

dependency_overrides:
  firebase_core_web: 3.10.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/dhs_icon.png"
